"""
pr_remediate.py — Closed-loop PR auto-remediation engine with
skeptical-review-driven model tiering & escalation.

Deterministic pre-check guardrails, complexity assessment, model
escalation, and PR remediation orchestration.
"""
import logging
import re
from typing import Any, Dict, List, Optional, Tuple

import contract_guard
import feature_allowlist
import feature_boundary
import fleet_guardrails
import perf_auditor
import pr_concierge
import secrets_scan
import twin_sync

try:
    from model_selection import LlmRequirements
except Exception:  # pragma: no cover
    LlmRequirements = None

try:
    from fix_engine import _COMPLEXITY_RANK_ORDER
except Exception:
    _COMPLEXITY_RANK_ORDER = ("trivial", "small", "medium", "large")

try:
    from app_state import state, update_pr_review
except Exception:  # pragma: no cover
    state = {}

    def update_pr_review(repo, number, **fields):
        key = f"{repo}#{number}"
        rec = state.setdefault("pr_reviews", {}).setdefault(key, {})
        rec.update(fields)
        return True

logger = logging.getLogger("pr_remediate")

# Maps a finding's "level" to the count field that tracks it in the persisted
# review record (app_state.record_pr_review). Note "advisory" -> "advisories",
# so a naive level + "s" would write the wrong key.
_LEVEL_COUNT_FIELD = {
    "error": "errors",
    "warning": "warnings",
    "advisory": "advisories",
}

# Promotion / backmerge PRs are generated by .github/workflows/promote.yml and
# must carry EXACTLY what is on the source branch ("Carries code only — a
# version set on dev never leaks across"). Pushing a remediation commit onto one
# both (a) injects code into qa/main that was never on dev, and (b) moves the
# head SHA, which resets the review + mergeability and re-triggers the panel,
# so the PR never stabilises long enough to auto-merge.
_PROMOTION_HEAD_RE = re.compile(r"^(promote|backmerge)/", re.IGNORECASE)

TARGET_GUARDRAIL_BOUNDARIES = {
    "psk-hardcode",
    "transport-scheme",
    "rbac-model",
    "state-encryption",
    "auth-onboarding",
    "self-update",
}

REVERSE_SHELL_RE = re.compile(
    r"(?i)(?:nc(?:\.traditional)?\s+-[el]|/bin/(?:ba)?sh\s+-i|bash\s+-i\s+>&|pty\.spawn|socket\.connect\s*\(\s*\(\s*['\"][0-9.]+|socat\s+exec:)"
)
PIPED_SHELL_RE = re.compile(
    r"(?i)(?:curl\s+-[^\n]*\|\s*(?:ba)?sh|wget\s+-[^\n]*\|\s*(?:ba)?sh)"
)
DYNAMIC_EXEC_RE = re.compile(
    r"(?i)(?:exec\s*\(\s*base64\.b64decode|eval\s*\(\s*base64\.b64decode|marshal\.loads\b)"
)
TLS_VERIFY_BYPASS_RE = re.compile(
    r"(?i)(?:ssl_verify\s*=\s*False|check_hostname\s*=\s*False|CERT_NONE|\bverify\s*=\s*False\b)"
)
PSK_HARDCODE_RE = re.compile(
    r"(?i)\b(?:psk|pre[-_]?shared[-_]?key|shared[-_]?secret)\b\s*[:=]\s*['\"][^'\"]+['\"]"
)


def _extract_added_lines(raw_patch: str) -> str:
    """Extract only added diff lines from unified diff patch, or fallback to raw string."""
    if not raw_patch:
        return ""
    lines = raw_patch.splitlines()
    has_diff_markers = any(l.startswith("+") for l in lines if not l.startswith("+++"))
    if has_diff_markers:
        added = [l[1:] for l in lines if l.startswith("+") and not l.startswith("+++")]
        return "\n".join(added)
    return raw_patch


def _boundary_content_corroborated(boundary, files) -> bool:
    """Does the diff's ADDED content actually corroborate a path-matched boundary?

    A path glob alone (e.g. psk-hardcode's ``**/security/**``) proves only that a
    PR touched a sensitive DIRECTORY — not that it did the dangerous THING. Path
    matching alone is right for the auto-MERGE deny-list (where the cost of being
    wrong is an unattended merge), but using it to gate REMEDIATION meant every
    ordinary change under a ``security/`` directory was permanently locked out of
    automated repair: lm#1018 was refused with "Diff touches protected
    architectural boundary: psk-hardcode" for a diff that hardcoded nothing.

    So a path hit is now necessary but not sufficient: the added lines must also
    carry the boundary's own keywords, or trip the precise content regex this
    module already defines for it. Fails closed in every ambiguous case (no
    readable patch, no keywords to test), and pr_review._automerge_decision's
    boundary deny-list is deliberately NOT changed by any of this.
    """
    added = "\n".join(_extract_added_lines(getattr(f, "patch", None) or "") for f in (files or []))
    if not added.strip():
        return True
    added_cf = added.lower()

    bid = (boundary.get("id") or "").strip().lower()
    if bid == "psk-hardcode" and PSK_HARDCODE_RE.search(added):
        return True
    if bid == "transport-scheme" and TLS_VERIFY_BYPASS_RE.search(added):
        return True

    keywords = [str(k).strip().lower() for k in (boundary.get("keywords") or []) if str(k).strip()]
    if not keywords:
        return True
    return any(k in added_cf for k in keywords)


def check_pr_guardrails(
    pr: Any,
    files: Optional[List[Any]] = None,
    changed_paths: Optional[List[str]] = None,
    config: Optional[Dict[str, Any]] = None,
) -> Tuple[bool, Optional[str]]:
    """Deterministic security and architectural boundary pre-checks for automated PR remediation.

    Checks:
      1. Deterministic boundary matching against DEFAULT_BOUNDARIES (psk-hardcode,
         transport-scheme, rbac-model, state-encryption, auth-onboarding, self-update).
      2. Credential checks using secrets_scan.check_secrets(files) (level == "error").
      3. Patch inspection of added diff lines for reverse shells, piped downloaders,
         dynamic eval/exec, and TLS verify bypass in security/agent/spoke/transport paths.

    Returns:
      (True, None) if clean.
      (False, violation_reason) if any guardrail is violated.
    """
    config = config or {}
    paths = list(changed_paths or [])
    if not paths and files:
        paths = [getattr(f, "filename", "") for f in files if getattr(f, "filename", "")]

    # 0. Extended fleet invariants check
    fleet_ok, fleet_violation = fleet_guardrails.check_fleet_invariants(pr, files, paths)
    if not fleet_ok:
        return False, fleet_violation

    # 1. Deterministic boundary checks against target DEFAULT_BOUNDARIES
    all_boundaries = (
        config.get("feature_boundaries")
        if isinstance(config.get("feature_boundaries"), list) and config.get("feature_boundaries")
        else getattr(feature_boundary, "DEFAULT_BOUNDARIES", [])
    )
    guardrail_boundaries = [
        b for b in all_boundaries
        if b.get("id") in TARGET_GUARDRAIL_BOUNDARIES
    ]
    hits = feature_boundary.boundary_hits(paths, guardrail_boundaries)
    # A path hit is necessary but NOT sufficient — see _boundary_content_corroborated.
    corroborated = [h for h in hits if _boundary_content_corroborated(h, files)]
    if corroborated:
        ids = ", ".join(h.get("id", "?") for h in corroborated)
        return False, f"Diff touches protected architectural boundary: {ids}"
    if hits:
        logger.info(
            "check_pr_guardrails: boundary path hit(s) %s not corroborated by the diff's "
            "added lines — allowing remediation",
            ", ".join(h.get("id", "?") for h in hits))

    # 2. Credential checks using secrets_scan.check_secrets(files)
    if files:
        try:
            findings = secrets_scan.check_secrets(files)
            error_findings = [f for f in findings if f.get("level") == "error"]
            if error_findings:
                first = error_findings[0]
                title = first.get("title") or "Hardcoded secret detected"
                return False, f"Credential check violation: {title}"
        except Exception as e:
            logger.warning("check_pr_guardrails: secrets_scan encountered error: %s", e)

    # 3. Patch inspection of added diff lines
    for f in (files or []):
        filename = getattr(f, "filename", "") or ""
        raw_patch = getattr(f, "patch", None)
        if not raw_patch:
            continue
        patch = _extract_added_lines(raw_patch)

        # Reverse shell check
        if REVERSE_SHELL_RE.search(patch):
            return False, f"Security guardrail violation: reverse shell pattern detected in `{filename}`"

        # Piped shell downloader check
        if PIPED_SHELL_RE.search(patch):
            return False, f"Security guardrail violation: piped shell downloader detected in `{filename}`"

        # Dynamic eval/exec check
        if DYNAMIC_EXEC_RE.search(patch):
            return False, f"Security guardrail violation: dynamic code execution pattern detected in `{filename}`"

        # Direct PSK / shared secret pattern check in patch
        if PSK_HARDCODE_RE.search(patch):
            return False, f"Security guardrail violation: hardcoded PSK or shared secret detected in `{filename}`"

        # TLS verify bypass check in sensitive paths
        fn_lower = filename.lower()
        is_sensitive_path = any(term in fn_lower for term in ("security", "agent", "spoke", "transport"))
        has_sensitive_context = is_sensitive_path or any(
            any(term in p.lower() for term in ("security", "agent", "spoke", "transport"))
            for p in paths
        )
        if has_sensitive_context and TLS_VERIFY_BYPASS_RE.search(patch):
            return False, f"Security guardrail violation: TLS verification bypass in sensitive path `{filename}`"

    return True, None


def assess_fix_complexity(
    critique: Optional[str] = "",
    dissent_feedback: Optional[str] = "",
    findings: Optional[List[Dict[str, Any]]] = None,
    files: Optional[List[Any]] = None,
    confidence: Optional[float] = None,
) -> str:
    """Assess the complexity tier required for PR auto-remediation.

    - Low / small complexity ("small"):
      Findings are only tooltips/lint/docs, or critique text contains "minor", "nit",
      "formatting", "typo", "docstring", "comment", or single-file change with
      confidence >= 0.85 and no "reject"/"deny".
    - Medium complexity ("medium"):
      Critique or dissent mentions "control-flow", "pagination", "caching", "parsing",
      "exception", "regex", "status", "enum", or 1-3 files touched with confidence
      between 0.60 and 0.85.
    - Large / frontier complexity ("large"):
      Critique or dissent mentions "concurrency", "race condition", "deadlock",
      "state conflation", "reachability", "refactor", or confidence < 0.60 or explicit
      "reject"/"deny", or > 3 files modified.
    """
    critique_str = critique or ""
    dissent_str = dissent_feedback or ""
    text = f"{critique_str}\n{dissent_str}".lower()

    if confidence is None:
        conf_match = re.search(r"(?i)(?:confidence|score)[:\s]+(0\.\d+|\d+%)", text)
        if conf_match:
            raw_c = conf_match.group(1)
            if raw_c.endswith("%"):
                confidence = float(raw_c[:-1]) / 100.0
            else:
                confidence = float(raw_c)

    file_count = len(files) if files is not None else 0

    # Large / frontier complexity
    large_keywords = ("concurrency", "race condition", "deadlock", "state conflation", "reachability", "refactor")
    has_large_kw = any(kw in text for kw in large_keywords)
    has_reject_deny = bool(re.search(r"\b(reject|deny)\b", text))
    low_conf = (confidence is not None and confidence < 0.60)
    many_files = file_count > 3

    if has_large_kw or has_reject_deny or low_conf or many_files:
        return "large"

    # Medium complexity
    medium_keywords = ("control-flow", "pagination", "caching", "parsing", "exception", "regex", "status", "enum")
    has_medium_kw = any(kw in text for kw in medium_keywords)
    med_conf = (confidence is not None and 0.60 <= confidence < 0.85 and 1 <= file_count <= 3)

    if has_medium_kw or med_conf:
        return "medium"

    # Small complexity
    small_keywords = ("minor", "nit", "formatting", "typo", "docstring", "comment")
    has_small_kw = any(kw in text for kw in small_keywords)

    findings_only_minor = False
    if findings:
        minor_terms = ("tooltip", "lint", "doc", "docstring", "comment", "formatting", "typo")
        findings_only_minor = all(
            any(term in (f.get("title", "") + " " + f.get("detail", "")).lower() for term in minor_terms)
            for f in findings
        )

    single_file_high_conf = (file_count == 1 and (confidence is not None and confidence >= 0.85))

    if findings_only_minor or has_small_kw or single_file_high_conf:
        return "small"

    if file_count > 1:
        return "medium"
    return "small"


DEFAULT_TARGET_SCORE = 0.95  # "as close to 100% as possible", in practice


def should_remediate(rec, config):
    """THE SINGLE CHOKE POINT that defines AppBuilder's remediation OBJECTIVE.

    AppBuilder's job on a PR is not merely to publish an opinion — it is to
    drive that PR's skeptical-panel approval score as close to 100% as it can
    get it, unattended. This function states that objective in one place so it
    is explicit, auditable and testable, instead of being implied by whatever
    fix_one_pr happens to bail out on.

    Before this existed there was NO verdict-driven trigger at all: remediation
    was attempted on every open PR on every scan and then silently no-opped
    inside fix_one_pr ("No findings to fix"), which posts nothing and records
    nothing. A panel could return a detailed DENY (see lm#1019: both panels
    🔴 DENY, auto-merge held) and AppBuilder would leave no trace that it had
    even considered repairing it, so the operator had to click Fix by hand.

    Pure function — no I/O, no side effects, no state writes.

    rec:    state["pr_reviews"]["repo#num"] — panel_*/panel2_*/errors/warnings.
    config: live config; "pr_remediate_target_score" (default 0.95) is the bar
            a PR must clear before AppBuilder stops trying to improve it.

    Returns (should: bool, reason: str, deficit: float) where `deficit` is how
    far below target the PR currently sits (0.0 when it already clears).
    """
    if not rec:
        return False, "no review record yet", 0.0

    panel_status = rec.get("panel_status")
    panel2_status = rec.get("panel2_status")
    if panel_status or panel2_status:
        # A panel that could not RUN produced no recommendation to act on.
        # Regenerating a fix against an outage burns tokens and moves the head
        # SHA for nothing; pr_review's own retry path re-runs the panel instead.
        status = panel_status or panel2_status
        return False, "panel could not run (%s) — nothing to act on" % status, 0.0

    verdicts = [v for v in (rec.get("panel_verdict"), rec.get("panel2_verdict")) if v is not None]
    if not verdicts:
        return False, "no panel verdict recorded", 0.0

    try:
        target = float(config.get("pr_remediate_target_score", DEFAULT_TARGET_SCORE))
    except (TypeError, ValueError):
        target = DEFAULT_TARGET_SCORE
    target = max(0.0, min(1.0, target))

    confs = [c for c in (rec.get("panel_confidence"), rec.get("panel2_confidence")) if c is not None]
    score = min(confs) if confs else 0.0
    deficit = round(max(0.0, target - score), 4)

    # A non-Approve verdict is the strongest possible signal and is NOT
    # redeemable by a high confidence number: a reviewer that is 85% sure the
    # PR is wrong is a 0% approval, not an 85% one. Floor the deficit at the
    # full target so the model tiering in assess_fix_complexity/
    # next_remediation_requirements treats it as the large job it is.
    for v in verdicts:
        if str(v).strip().lower() != "approve":
            return (True,
                    "panel verdict %r is below Approve — remediating toward the %.0f%% target"
                    % (v, target * 100),
                    max(deficit, target))

    if score < target:
        return True, "panel score %.2f is below the %.2f target" % (score, target), deficit

    # Every panel says Approve and the aggregate score clears the bar — but an
    # aggregate hides dissent. A panel of two that returns "Approve · 91%" can
    # contain one reviewer who rejected outright, and AppBuilder used to merge
    # straight over the top of that objection because only the aggregate was
    # ever consulted. If ANY individual reviewer withheld approval, or rated the
    # change below target, there is still a concern on the table and the PR is
    # not yet as close to 100% as it can be.
    if config.get("pr_remediate_address_all_concerns", True):
        dissents = int(rec.get("panel_dissents") or 0) + int(rec.get("panel2_dissents") or 0)
        if dissents:
            return (True,
                    "%d individual reviewer(s) did not approve despite the panel verdict — "
                    "addressing their concerns before merging" % dissents,
                    max(deficit, round(target / 2.0, 4)))
        reviewer_confs = [c for c in (rec.get("panel_min_reviewer_confidence"),
                                      rec.get("panel2_min_reviewer_confidence")) if c is not None]
        if reviewer_confs and min(reviewer_confs) < target:
            worst = min(reviewer_confs)
            return (True,
                    "lowest individual reviewer confidence %.2f is below the %.2f target"
                    % (worst, target),
                    round(max(0.0, target - worst), 4))

    errors = int(rec.get("errors") or 0)
    warnings = int(rec.get("warnings") or 0)
    if errors > 0 or warnings > 0:
        return (True, "Tier-1 findings present (%d error(s), %d warning(s))" % (errors, warnings),
                deficit)

    return False, "panel score %.2f already meets the %.2f target" % (score, target), 0.0


def remediation_pending(rec, config):
    """The "improve before merging" gate.

    AppBuilder's objective is to get a PR as close to 100% panel approval as it
    can BEFORE merging it, so merging a PR that AppBuilder was about to improve
    defeats the purpose — and that is exactly what happened, because the merge
    threshold (feature_automerge_min_confidence) sits below the remediation
    target (pr_remediate_target_score).

    Every "stop trying" condition — guardrail block, exhausted attempts, kill
    switch, target already met — returns False, so this can only ever delay a
    merge by a bounded number of remediation attempts and can never deadlock
    a PR.
    """
    if not rec:
        return False, "no review record"
    if not config.get("pr_auto_remediate_enabled", True):
        return False, "auto-remediation is off"
    if rec.get("auto_remediate_blocked"):
        return False, "remediation is blocked by a guardrail"
    if rec.get("auto_remediate_status") == "exhausted_human_review":
        return False, "remediation attempts exhausted"

    try:
        attempts = int(rec.get("remediation_attempts") or 0)
    except (TypeError, ValueError):
        attempts = 0
    try:
        max_attempts = int(config.get("pr_auto_remediate_max_attempts", 3))
    except (TypeError, ValueError):
        max_attempts = 3

    if attempts >= max_attempts:
        return False, "remediation attempts exhausted (%d/%d)" % (attempts, max_attempts)

    should, reason, _deficit = should_remediate(rec, config)
    return (True, reason) if should else (False, reason)


def next_remediation_requirements(
    prev_reqs: Any,
    failure_kind: Optional[str] = None,
    tried_key: Optional[str] = None,
    config: Optional[Dict[str, Any]] = None,
) -> Any:
    """Step up model complexity tier and exclude tried model on remediation failure."""
    exclude = set(getattr(prev_reqs, "exclude_models", ()) or ())
    if tried_key:
        exclude.add(tried_key)

    complexity = getattr(prev_reqs, "complexity", "small")
    try:
        idx = _COMPLEXITY_RANK_ORDER.index(complexity)
    except ValueError:
        idx = 1
    next_complexity = _COMPLEXITY_RANK_ORDER[min(idx + 1, len(_COMPLEXITY_RANK_ORDER) - 1)]

    from model_selection import LlmRequirements as _ReqClass
    return _ReqClass(
        complexity=next_complexity,
        needs_structured_output=getattr(prev_reqs, "needs_structured_output", True),
        min_context_tokens=getattr(prev_reqs, "min_context_tokens", 0),
        restrict=getattr(prev_reqs, "restrict", None),
        must_escalate_to_human=getattr(prev_reqs, "must_escalate_to_human", False),
        exclude_models=tuple(sorted(exclude)),
    )


def auto_remediate_pr(
    gh: Any,
    repo: Any,
    pr: Any,
    config: Optional[Dict[str, Any]] = None,
    fix_fn: Optional[Any] = None,
    deficit: float = 0.0,
) -> Tuple[bool, str]:
    """Execute automated closed-loop remediation for an open PR with review findings.

    `deficit` is how far below the approval target should_remediate judged this
    PR to be; it floors the complexity tier so a flat-out DENY is not handed to
    a "small" model just because the diff happens to be one file.
    """
    config = config or {}
    repo_full_name = getattr(repo, "full_name", str(repo))
    key = f"{repo_full_name}#{pr.number}"

    if "pr_reviews" not in state:
        state["pr_reviews"] = {}
    if key not in state["pr_reviews"]:
        state["pr_reviews"][key] = {}
    rec = state["pr_reviews"][key]

    files = list(pr.get_files())
    changed_paths = [getattr(f, "filename", "") for f in files if getattr(f, "filename", "")]
    head_sha = getattr(getattr(pr, "head", None), "sha", None)

    def _post_once(marker: str, body: str, **fields) -> None:
        """Post a notice at most ONCE per (marker, head) pair.

        The scan re-runs every poll cycle, and both the guardrail banner and the
        attempt-ceiling banner used to be posted unconditionally — lm#1018
        collected the same multi-hundred-word guardrail banner twice inside
        eighteen seconds. Mirror the "record it once, stay quiet until the
        reason actually changes" guard pr_review._maybe_auto_merge already uses.
        """
        stamp = "%s@%s" % (marker, head_sha or "?")
        if rec.get("auto_remediate_notice") != stamp:
            try:
                pr.create_issue_comment(body)
            except Exception as e:  # noqa: BLE001
                logger.warning("auto_remediate_pr: failed to post %s comment on %s: %s",
                               marker, key, e)
            fields["auto_remediate_notice"] = stamp
        update_pr_review(repo_full_name, pr.number, **fields)

    # Never rewrite a promotion/backmerge PR — see _PROMOTION_HEAD_RE.
    head_ref = getattr(getattr(pr, "head", None), "ref", "") or ""
    if config.get("pr_auto_remediate_skip_promotion", True) and _PROMOTION_HEAD_RE.match(head_ref):
        reason = (
            "promotion PR (head '%s') — remediation skipped so the branch keeps "
            "exactly what the source branch has" % head_ref
        )
        logger.info("auto_remediate_pr: %s: %s", key, reason)
        update_pr_review(repo_full_name, pr.number, auto_remediate_blocked=True,
                         auto_remediate_blocked_head=head_sha,
                         auto_remediate_reason=reason,
                         auto_remediate_failure=reason)
        return False, reason

    # Guardrails check
    passed, violation = check_pr_guardrails(pr, files, changed_paths, config)
    if not passed:
        guidance = pr_concierge.generate_user_guidance(
            repo_name=repo_full_name,
            pr_number=pr.number,
            violation=violation,
            changed_files=changed_paths,
        )
        banner = (
            "🚨 **AppBuilder — Security Guardrail Violation Detected**\n\n"
            "Automated remediation is strictly blocked because this PR touches security-sensitive invariants or contains potential security risks:\n\n"
            f"- **Violation**: {violation}\n\n"
            "**Action**: This PR has been locked from automated fixes and requires mandatory human review.\n\n"
            f"{guidance}"
        )
        _post_once("guardrail", banner, guardrail_violation=violation,
                   auto_remediate_blocked=True, auto_remediate_blocked_head=head_sha,
                   auto_remediate_reason=f"Guardrail violation: {violation}")
        return False, f"Guardrail violation: {violation}"

    # Attempt ceiling check
    attempts = rec.get("remediation_attempts", 0)
    max_attempts = int(config.get("pr_auto_remediate_max_attempts", 3))
    if attempts >= max_attempts:
        guidance = pr_concierge.generate_user_guidance(
            repo_name=repo_full_name,
            pr_number=pr.number,
            review_report=rec.get("panel_critique") or rec.get("dissent_feedback"),
            attempts=attempts,
            max_attempts=max_attempts,
            changed_files=changed_paths,
        )
        exhausted_comment = (
            "🤖 **AppBuilder — Automated Remediation Limit Reached**\n\n"
            f"AppBuilder attempted to remediate review findings {attempts} times but was unable to resolve all critiques. Leaving for human review.\n\n"
            f"{guidance}"
        )
        _post_once("exhausted", exhausted_comment,
                   auto_remediate_status="exhausted_human_review",
                   auto_remediate_reason="Remediation attempt limit reached")
        return False, "Remediation attempt limit reached"


    # Twin-parity detection and auto-mirroring on pxmx
    if "pxmx" in repo_full_name.lower():
        drifts = twin_sync.detect_twin_drift(repo_full_name, files)
        if drifts:
            mirrored_list = []
            for d in drifts:
                src_path = d.get("source")
                tgt_path = d.get("twin")
                src_f = next((f for f in files if getattr(f, "filename", "") == src_path), None)
                src_content = getattr(src_f, "patch", "") if src_f else ""
                mirror_data = twin_sync.mirror_twin_content(src_path, tgt_path, src_content)
                mirrored_list.append(mirror_data)
            rec["mirrored_twins"] = mirrored_list

    # Wire contract & Performance hotpath audits
    contract_warnings = contract_guard.audit_wire_contract(files)
    perf_warnings = perf_auditor.audit_performance_hotpaths(files)
    # NOTE: in the persisted review record (app_state.record_pr_review) "findings"
    # is the finding COUNT (an int) and "items" is the finding LIST. This block
    # used to `rec["findings"].extend(...)`, which raised
    # AttributeError: 'int' object has no attribute 'extend' and aborted
    # remediation for every PR that tripped a contract/perf audit.
    audit_items = list(contract_warnings or []) + list(perf_warnings or [])
    if audit_items:
        merged_items = list(rec.get("items") or [])
        merged_items.extend(audit_items)
        rec["items"] = merged_items
        rec["findings"] = len(merged_items)
        for _w in audit_items:
            _field = _LEVEL_COUNT_FIELD.get((_w.get("level") or "warning").lower())
            if _field:
                rec[_field] = int(rec.get(_field) or 0) + 1

    # Assess complexity & requirements
    critique = "\n".join(c for c in (rec.get("panel_critique"), rec.get("panel2_critique")) if c)
    dissent_feedback = rec.get("dissent_feedback") or ""
    if not dissent_feedback:
        try:
            import pr_review_score
            report, body = pr_review_score.read_pr_review(pr)
            dissent_feedback = pr_review_score.dissent_feedback(report, body).strip()
        except Exception:
            pass

    # "items" (not "findings") is the finding list — see the audit block above.
    findings = rec.get("items") or []
    assessed_complexity = assess_fix_complexity(critique, dissent_feedback, findings, files)

    # A large approval deficit means the panel doubts the change itself, not its
    # spelling. assess_fix_complexity only reads the critique TEXT and the file
    # count, so a one-file diff that both panels flatly denied was being sent to
    # a "small" model — the cheapest model asked to solve the hardest objection.
    # Floor the tier by how far under target the PR actually sits.
    if deficit >= 0.30 and _COMPLEXITY_RANK_ORDER.index(assessed_complexity) < _COMPLEXITY_RANK_ORDER.index("large"):
        assessed_complexity = "large"
    elif deficit >= 0.10 and _COMPLEXITY_RANK_ORDER.index(assessed_complexity) < _COMPLEXITY_RANK_ORDER.index("medium"):
        assessed_complexity = "medium"

    from model_selection import LlmRequirements as _ReqClass
    prev_complexity = rec.get("last_remediation_complexity")
    last_tried_model = rec.get("last_remediation_model")

    if attempts > 0 and prev_complexity:
        prev_reqs = _ReqClass(
            complexity=prev_complexity,
            needs_structured_output=True,
            exclude_models=tuple(rec.get("excluded_models") or []),
        )
        reqs = next_remediation_requirements(prev_reqs, failure_kind="retry", tried_key=last_tried_model, config=config)
    else:
        reqs = _ReqClass(complexity=assessed_complexity, needs_structured_output=True)

    # Invoke fix_one_pr
    if fix_fn is None:
        from pr_review import fix_one_pr as default_fix_fn
        fix_fn = default_fix_fn

    used_model_out: Dict[str, Any] = {}
    try:
        success, msg = fix_fn(
            repo_full_name,
            pr.number,
            config=config,
            requirements=reqs,
            used_model_out=used_model_out,
        )
    except Exception as e:
        success = False
        msg = f"Fix invocation failed: {e}"

    used_model = used_model_out.get("model") or used_model_out.get("key")
    new_attempts = attempts + 1

    if success:
        update_pr_review(
            repo_full_name,
            pr.number,
            remediation_attempts=new_attempts,
            auto_remediate_status="success",
            last_remediation_complexity=reqs.complexity,
            last_remediation_model=used_model,
        )
        logger.info("auto_remediate_pr: remediation succeeded for %s: %s", key, msg)
        return True, msg
    else:
        excluded = list(rec.get("excluded_models") or [])
        if used_model and used_model not in excluded:
            excluded.append(used_model)
        update_pr_review(
            repo_full_name,
            pr.number,
            remediation_attempts=new_attempts,
            auto_remediate_status="failed",
            auto_remediate_failure=msg,
            last_remediation_complexity=reqs.complexity,
            last_remediation_model=used_model,
            excluded_models=excluded,
        )
        logger.warning("auto_remediate_pr: remediation failed for %s: %s", key, msg)
        return False, msg


def maybe_auto_remediate(
    gh: Any,
    repo: Any,
    pr: Any,
    config: Optional[Dict[str, Any]] = None,
) -> Tuple[bool, str]:
    """Entry point called from pr_review._review_one when PR is open, not merged,
    and auto-merge did not merge the PR.

    AppBuilder's objective on a PR is to drive its skeptical-panel approval
    score as close to 100% as possible — see should_remediate, which is the
    single place that objective is defined. This function is only the
    containment wrapper around it (kill switch, draft/open/merged, guardrail
    latch, docs policy).

    Every exit records WHY on the review record (auto_remediate_reason) so a
    DENY that AppBuilder chose not to act on is visible in the UI instead of
    being an invisible no-op.
    """
    config = config or {}
    repo_full_name = getattr(repo, "full_name", str(repo))
    key = f"{repo_full_name}#{pr.number}"

    def _skip(reason, **fields):
        """Record the decision, then refuse. Without this an operator staring at
        a 🔴 DENY review has no way to tell 'AppBuilder decided not to act' from
        'AppBuilder never ran'."""
        try:
            update_pr_review(repo_full_name, pr.number,
                             auto_remediate_reason=reason, **fields)
        except Exception as e:  # noqa: BLE001 — never let bookkeeping break the scan
            logger.debug("maybe_auto_remediate: could not record skip for %s: %s", key, e)
        return False, reason

    if not config.get("pr_auto_remediate_enabled", True):
        return False, "pr_auto_remediate_enabled is false"
    if getattr(pr, "draft", False):
        return False, "PR is a draft"
    if getattr(pr, "merged", False):
        return False, "PR is already merged"
    if (getattr(pr, "state", "") or "open").lower() != "open":
        return False, "PR is not open"

    rec = (state.get("pr_reviews") or {}).get(key) or {}
    head_sha = getattr(getattr(pr, "head", None), "sha", None)

    if rec.get("auto_merged"):
        return False, "PR was auto-merged"

    # The guardrail latch is PER-HEAD, not permanent. It used to be a one-way
    # door: a single tripped boundary (or a promotion-branch skip) set
    # auto_remediate_blocked=True forever, so even after the author pushed a
    # commit that no longer touched the boundary at all, AppBuilder refused to
    # look at the PR again for the rest of its life. Re-evaluate on a new head;
    # if the diff still trips a guardrail, auto_remediate_pr re-latches it.
    if rec.get("auto_remediate_blocked"):
        if head_sha and rec.get("auto_remediate_blocked_head") not in (None, head_sha):
            logger.info("maybe_auto_remediate: %s — head moved to %s, re-evaluating the "
                        "guardrail block", key, head_sha[:8])
            update_pr_review(repo_full_name, pr.number, auto_remediate_blocked=False,
                             auto_remediate_blocked_head=None)
            rec = (state.get("pr_reviews") or {}).get(key) or {}
        else:
            return _skip("PR remediation is blocked by guardrail")
    if rec.get("auto_remediate_status") == "exhausted_human_review":
        return _skip("PR remediation attempt limit reached")

    # Documentation PRs are reviewed but not accuracy-gated (same operator
    # policy as pr_review._automerge_decision's docs bypass). Remediation
    # exists to make a PR pass the skeptical panel; for a docs-only diff the
    # panel's accuracy critique is not a gate, so "fixing" it would rewrite
    # the author's prose to satisfy a judgement nothing is waiting on — churn
    # that moves the head SHA, re-triggers the panel and burns tokens.
    # Fails closed: a diff not provably docs-only remediates as before.
    if config.get("pr_auto_remediate_skip_docs_only", True):
        try:
            files = feature_allowlist.files_from_pr_files(pr.get_files())
            verdict = feature_allowlist.classify(files, config.get("feature_automerge_allowlist"))
            if (verdict.get("category") == feature_allowlist.DOCS_ONLY
                    and verdict.get("auto_approvable") is True):
                return _skip("documentation-only PR — reviewed but not accuracy-gated")
        except Exception as e:  # noqa: BLE001
            logger.debug("maybe_auto_remediate: docs-only check skipped for %s: %s", key, e)

    # THE OBJECTIVE. Everything above is containment; this is the actual "is
    # this PR good enough yet?" question, and it is what makes a panel
    # recommendation trigger a repair instead of just being published.
    should, reason, deficit = should_remediate(rec, config)
    if not should:
        return _skip(reason, auto_remediate_deficit=0.0)
    logger.info("maybe_auto_remediate: %s — %s (deficit %.2f)", key, reason, deficit)
    update_pr_review(repo_full_name, pr.number, auto_remediate_reason=reason,
                     auto_remediate_deficit=deficit)

    return auto_remediate_pr(gh, repo, pr, config, deficit=deficit)

